import { NavLink, Outlet, useLocation, useNavigate } from "react-router-dom";
import { useAuth } from "../../context/AuthContext";
import { useEffect, useMemo, useState } from "react";
import { Bot, ChevronRight, FileText, GitBranch, Inbox, LayoutGrid, LifeBuoy, LogOut, Mail, Menu, MessageCircle, Phone, Plus, Search, Settings, Sparkles, Users, X, Zap } from "lucide-react";

const groups = [
  { label: "Workspace", items: [["/app", "Overview", LayoutGrid], ["/app/analytics", "Analytics", Zap]] },
  { label: "Customers", items: [["/app/contacts", "Customers", Users], ["/app/pipeline", "Leads & pipeline", GitBranch], ["/app/activities", "Tasks", FileText]] },
  { label: "Communications", items: [["/app/inbox", "Inbox", Inbox], ["/app/whatsapp", "WhatsApp", MessageCircle], ["/app/emails", "Email", Mail], ["/app/calls", "Calls & IVR", Phone], ["/app/campaigns", "Campaigns", Sparkles]] },
  { label: "Operations", items: [["/app/tickets", "Tickets", LifeBuoy], ["/app/automations", "Automations", Bot], ["/app/settings", "Settings", Settings]] },
];
const allItems = groups.flatMap((g) => g.items.map(([to, label, icon]) => ({ to, label, icon, group: g.label })));
const titleFor = (pathname) => allItems.find((item) => pathname === item.to || pathname.startsWith(`${item.to}/`))?.label || "Workspace";

function CommandMenu({ open, onClose }) {
  const navigate = useNavigate(); const [query, setQuery] = useState("");
  useEffect(() => { if (open) setQuery(""); }, [open]);
  if (!open) return null;
  const matches = allItems.filter((item) => item.label.toLowerCase().includes(query.toLowerCase()));
  const go = (to) => { navigate(to); onClose(); };
  return <div className="fixed inset-0 z-[70] grid place-items-start bg-slate-950/40 px-4 pt-[12vh] backdrop-blur-sm" onMouseDown={onClose}>
    <section role="dialog" aria-modal="true" aria-label="Search workspace" className="command-menu w-full max-w-xl overflow-hidden rounded-2xl border border-border bg-surface shadow-2xl" onMouseDown={(e) => e.stopPropagation()}>
      <div className="flex items-center gap-3 border-b border-border px-4"><Search className="size-5 text-inkSecondary" /><input autoFocus value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search pages and tools..." className="h-14 w-full bg-transparent text-sm outline-none" /><kbd className="hidden rounded border border-border px-1.5 py-0.5 text-[10px] text-inkSecondary sm:block">Esc</kbd></div>
      <div className="max-h-[50vh] overflow-y-auto p-2">{matches.length ? matches.map(({ to, label, icon: Icon, group }) => <button key={to} onClick={() => go(to)} className="flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left hover:bg-bg"><span className="grid size-9 place-items-center rounded-lg bg-bg text-brand"><Icon className="size-4" /></span><span className="min-w-0 flex-1"><span className="block text-sm font-semibold">{label}</span><span className="block text-xs text-inkSecondary">{group}</span></span><ChevronRight className="size-4 text-inkSecondary" /></button>) : <p className="px-3 py-10 text-center text-sm text-inkSecondary">No matching workspace tools.</p>}</div>
    </section>
  </div>;
}

export default function AppShell() {
  const { user, logout } = useAuth(); const navigate = useNavigate(); const location = useLocation();
  const [mobileOpen, setMobileOpen] = useState(false); const [commandOpen, setCommandOpen] = useState(false);
  const isWhatsAppWorkspace = location.pathname === "/app/whatsapp";
  useEffect(() => { const handler = (e) => { if ((e.metaKey || e.ctrlKey) && e.key.toLowerCase() === "k") { e.preventDefault(); setCommandOpen(true); } if (e.key === "Escape") { setCommandOpen(false); setMobileOpen(false); } }; window.addEventListener("keydown", handler); return () => window.removeEventListener("keydown", handler); }, []);
  const initials = useMemo(() => (user?.name || "?").slice(0, 1).toUpperCase(), [user]);
  const nav = <><div className="flex h-[74px] items-center border-b border-border px-5"><button onClick={() => navigate("/app")} className="flex items-center gap-3 text-left"><span className="grid size-9 place-items-center rounded-xl bg-brand font-heading text-lg font-black text-white shadow-lg shadow-brand/20">B</span><span><b className="block font-heading text-lg tracking-tight">BillByteKOT</b><small className="block text-[10px] font-medium text-inkSecondary">Customer operations</small></span></button><button onClick={() => setMobileOpen(false)} className="ml-auto md:hidden" aria-label="Close navigation"><X /></button></div><nav className="flex-1 overflow-y-auto p-3" aria-label="Main navigation">{groups.map(({ label, items }) => <div key={label} className="mb-5"><p className="px-3 pb-2 text-[10px] font-bold uppercase tracking-[.14em] text-inkSecondary">{label}</p>{items.map(([to, itemLabel, Icon]) => <NavLink key={to} to={to} end={to === "/app"} onClick={() => setMobileOpen(false)} className={({ isActive }) => `nav-item ${isActive ? "nav-item-active" : ""}`}><Icon className="size-4" /><span>{itemLabel}</span></NavLink>)}</div>)}</nav><div className="border-t border-border p-3"><button onClick={() => navigate("/app/contacts?new=1")} className="btn-primary w-full"><Plus className="size-4" />New customer</button><div className="mt-3 flex items-center gap-3 rounded-xl bg-bg p-3"><span className="grid size-8 place-items-center rounded-full bg-ink text-xs font-bold text-white">{initials}</span><span className="min-w-0 flex-1"><b className="block truncate text-xs">{user?.name || "Your workspace"}</b><small className="block truncate text-[10px] text-inkSecondary">{user?.email}</small></span></div><button onClick={() => { logout(); navigate("/"); }} className="mt-2 flex w-full items-center justify-center gap-2 rounded-xl py-2 text-xs font-semibold text-inkSecondary hover:bg-bg hover:text-ink"><LogOut className="size-4" />Sign out</button></div></>;
  return <div className="min-h-screen bg-bg"><aside className="fixed inset-y-0 left-0 z-40 hidden w-[258px] flex-col border-r border-border bg-surface md:flex">{nav}</aside>{mobileOpen && <><button className="fixed inset-0 z-40 bg-slate-950/35 md:hidden" onClick={() => setMobileOpen(false)} aria-label="Close menu"/><aside className="fixed inset-y-0 left-0 z-50 flex w-[min(86vw,320px)] flex-col bg-surface shadow-2xl md:hidden">{nav}</aside></>}<main className="min-w-0 pb-20 md:pl-[258px] md:pb-0"><header className={`app-header ${isWhatsAppWorkspace ? "whatsapp-app-header" : ""}`}><div className="flex min-w-0 items-center gap-3"><button className="icon-button md:hidden" onClick={() => setMobileOpen(true)} aria-label="Open menu"><Menu className="size-5" /></button><div className="hidden min-w-0 md:block"><p className="truncate text-sm font-semibold">{titleFor(location.pathname)}</p><p className="text-[11px] text-inkSecondary">Your customer workspace</p></div></div><div className="flex items-center gap-2"><button className="search-trigger hidden sm:flex" onClick={() => setCommandOpen(true)}><Search className="size-4" /><span>Search</span><kbd>Ctrl K</kbd></button><button className="btn-primary hidden sm:flex" onClick={() => navigate("/app/contacts?new=1")}><Plus className="size-4" />Create</button></div></header><Outlet /></main><nav className="mobile-nav md:hidden" aria-label="Mobile navigation">{[["/app", "Home", LayoutGrid], ["/app/inbox", "Inbox", Inbox], ["/app/contacts", "Customers", Users], ["/app/activities", "Tasks", FileText]].map(([to, label, Icon]) => <NavLink key={to} end={to === "/app"} to={to}><Icon className="size-5"/><span>{label}</span></NavLink>)}<button onClick={() => setMobileOpen(true)}><Menu className="size-5"/><span>More</span></button></nav><CommandMenu open={commandOpen} onClose={() => setCommandOpen(false)} /></div>;
}
