import { useLocation, useNavigate } from "react-router-dom";
import { ArrowUpRight, Check, Filter, Inbox, Megaphone, Phone, Plus, Search, Sparkles, Users, Zap, Bot, FileText } from "lucide-react";

const configs = {
  inbox: { eyebrow: "Communications / inbox", title: "Every conversation, one clear queue.", description: "Prioritize customer replies without losing the context from your other channels.", icon: Inbox, primary: "Open WhatsApp", action: "/app/whatsapp", items: [{ name: "WhatsApp conversations", detail: "Continue in the connected channel", status: "Available" }, { name: "Email threads", detail: "Keep replies and follow-ups together", status: "Available" }, { name: "Tickets and notes", detail: "Resolve operational work beside messages", status: "Available" }] },
  campaigns: { eyebrow: "Customer growth / campaigns", title: "Reach the right regulars.", description: "Build thoughtful audience-led campaigns from the customer data you already own.", icon: Megaphone, primary: "Create campaign", action: "#create", items: [{ name: "Audience builder", detail: "Segment by customer details and activity", status: "Ready" }, { name: "Consent-aware sending", detail: "Opt-outs and exclusions stay visible", status: "Protected" }, { name: "Performance", detail: "Provider events power reported metrics", status: "Live data only" }] },
  templates: { eyebrow: "Communications / library", title: "A better starting point for every message.", description: "Keep approved copy, reusable email content, and operational responses close to the team.", icon: Sparkles, primary: "Add template", action: "#create", items: [{ name: "WhatsApp templates", detail: "Approval state is shown from the provider", status: "Connected" }, { name: "Email templates", detail: "Reuse your best customer replies", status: "Ready" }, { name: "Internal playbooks", detail: "Give agents a consistent next step", status: "Ready" }] },
  analytics: { eyebrow: "Overview / analytics", title: "Know what deserves attention.", description: "Read conversion, follow-up, and channel signals without inventing metrics your providers do not expose.", icon: Zap, primary: "Export report", action: "#export", items: [{ name: "Lead conversion", detail: "Pipeline stages from your CRM", status: "Available" }, { name: "Follow-up completion", detail: "Tasks completed by your team", status: "Available" }, { name: "Channel performance", detail: "Only persisted delivery events", status: "Live data only" }] },
  calls: { eyebrow: "Communications / voice", title: "Make every call accountable.", description: "Keep call history, dispositions, callbacks, and IVR design in one place. Live calling activates only after a real provider is connected.", icon: Phone, primary: "Configure voice", action: "/app/channels", items: [{ name: "Call history", detail: "Inbound, outbound, missed, duration, and status", status: "Provider events" }, { name: "IVR builder", detail: "Greeting, routing, business hours, queues, and voicemail", status: "Design ready" }, { name: "Follow-up outcomes", detail: "Turn dispositions into tasks and customer timeline events", status: "CRM ready" }] },
  automations: { eyebrow: "Operations / automation", title: "Turn repeat work into rules.", description: "Create simple IF → THEN workflows for tickets, customers, messages, SLAs, and follow-ups with visible ownership.", icon: Bot, primary: "Create automation", action: "#create", items: [{ name: "Event triggers", detail: "New ticket, chat, message, customer, or campaign event", status: "Ready" }, { name: "Conditions and delays", detail: "Branch by priority, team, customer type, or time", status: "Ready" }, { name: "Audit-friendly actions", detail: "Assign, notify, tag, create task, or escalate", status: "Persisted" }] },
  knowledge: { eyebrow: "Self service / knowledge base", title: "Give customers the answer first.", description: "Organize FAQs, guides, and private playbooks so agents and future chatbots can use the same source of truth.", icon: FileText, primary: "Create article", action: "#create", items: [{ name: "Articles and FAQs", detail: "Draft, review, publish, and archive content", status: "Ready" }, { name: "Private playbooks", detail: "Internal notes and agent-only procedures", status: "Protected" }, { name: "Help center", detail: "Public search and ticket deflection surface", status: "Connect route" }] },
};

export default function CRMWorkspace({ type }) {
  const config = configs[type] || configs.inbox; const Icon = config.icon; const navigate = useNavigate(); const location = useLocation();
  return <div className="min-h-screen"><div className="mx-auto max-w-[1200px] p-4 md:p-8"><div className="mb-8 flex flex-col gap-5 border-b border-border pb-8 md:flex-row md:items-end md:justify-between"><div><div className="mb-3 flex items-center gap-2 font-mono text-[10px] uppercase tracking-[0.2em] text-brand"><Icon className="size-3.5" /> {config.eyebrow}</div><h1 className="max-w-3xl text-balance font-heading text-4xl font-black tracking-tight md:text-5xl">{config.title}</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-inkSecondary">{config.description}</p></div><button onClick={() => config.action.startsWith("/") ? navigate(config.action) : document.getElementById("workspace-action")?.focus()} className="flex shrink-0 items-center justify-center gap-2 rounded-xl bg-brand px-4 py-3 text-xs font-bold text-white hover:bg-brand-hover"><Plus className="size-4" /> {config.primary}</button></div><div className="mb-5 flex flex-col gap-3 sm:flex-row"><div className="flex flex-1 items-center gap-2 rounded-xl border border-border bg-surface px-3 py-2.5"><Search className="size-4 text-inkSecondary" /><input id="workspace-action" aria-label="Search workspace" className="w-full bg-transparent text-sm outline-none placeholder:text-inkSecondary" placeholder="Search this workspace" /></div><button className="flex items-center justify-center gap-2 rounded-xl border border-border bg-surface px-4 py-2.5 text-xs font-bold"><Filter className="size-4" /> Filters</button></div><div className="grid gap-3 md:grid-cols-3">{config.items.map((item) => <article key={item.name} className="rounded-2xl border border-border bg-surface p-5 transition hover:-translate-y-0.5 hover:border-ink"><div className="flex items-start justify-between gap-3"><div className="grid size-10 place-items-center rounded-xl bg-bg text-brand"><Check className="size-4" /></div><span className="rounded-full bg-bg px-2.5 py-1 font-mono text-[9px] uppercase tracking-wider text-inkSecondary">{item.status}</span></div><h2 className="mt-5 font-heading text-lg font-black">{item.name}</h2><p className="mt-2 text-xs leading-5 text-inkSecondary">{item.detail}</p><button className="mt-5 flex items-center gap-1 text-xs font-bold text-brand">Explore <ArrowUpRight className="size-3.5" /></button></article>)}</div><div className="mt-5 rounded-2xl border border-border bg-ink p-5 text-white md:p-6"><div className="flex items-start gap-3"><Users className="mt-0.5 size-5 text-brand" /><div><h2 className="font-heading text-xl font-black">Built around real customer context.</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-white/65">Connect the channels you use, then keep assignments, consent, and next actions visible. Unsupported provider features stay clearly marked instead of pretending to be live.</p></div></div></div></div></div>;
}
