import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import api from "../lib/api";
import { ArrowUpRight, CheckCircle2, Clock3, MessageCircle, Plus, Sparkles, TrendingUp, Users, WalletCards } from "lucide-react";
import { toast } from "sonner";

const Stat = ({ label, value, detail, icon: Icon, tone = "plain" }) => <div className={`rounded-2xl border border-border p-5 ${tone === "brand" ? "bg-brand text-white" : "bg-surface"}`}><div className="flex items-center justify-between"><span className={`font-mono text-[10px] uppercase tracking-[0.16em] ${tone === "brand" ? "text-white/70" : "text-inkSecondary"}`}>{label}</span><Icon className="size-4" /></div><div className="mt-4 font-heading text-3xl font-black tracking-tight">{value}</div><div className={`mt-1 text-xs ${tone === "brand" ? "text-white/75" : "text-inkSecondary"}`}>{detail}</div></div>;
const Action = ({ icon: Icon, title, detail, to, onClick }) => <button onClick={onClick || (() => to && (window.location.href = to))} className="group flex w-full items-center gap-3 rounded-xl border border-border bg-surface p-3 text-left transition hover:-translate-y-0.5 hover:border-ink"><span className="grid size-9 shrink-0 place-items-center rounded-lg bg-bg text-brand"><Icon className="size-4" /></span><span className="min-w-0 flex-1"><span className="block text-xs font-bold">{title}</span><span className="block truncate text-[11px] text-inkSecondary">{detail}</span></span><ArrowUpRight className="size-4 text-inkSecondary transition group-hover:text-ink" /></button>;

export default function Dashboard() {
    const [stats, setStats] = useState(null); const [insight, setInsight] = useState(""); const [loading, setLoading] = useState(false); const [statsLoading, setStatsLoading] = useState(true); const [statsError, setStatsError] = useState(false); const navigate = useNavigate();
    const loadStats = () => { setStatsLoading(true); setStatsError(false); api.get("/dashboard/stats").then(({ data }) => setStats(data)).catch(() => { setStatsError(true); toast.error("Could not load your workspace"); }).finally(() => setStatsLoading(false)); };
    useEffect(() => { loadStats(); }, []);
    const money = (n) => n == null ? "—" : new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(n);
    const metric = (value) => statsLoading ? "…" : statsError ? "—" : (value ?? "—");
    const askAI = async () => { setLoading(true); try { const { data } = await api.post("/ai/next-best-action", {}); setInsight(data.recommendation); } catch (err) { toast.error(err.response?.data?.detail || "AI recommendation unavailable"); } finally { setLoading(false); } };
    return <div className="min-h-screen"><div className="mx-auto max-w-[1440px] p-4 md:p-8" data-testid="dashboard-page"><div className="mb-8 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><div className="mb-3 flex items-center gap-2 font-mono text-[10px] uppercase tracking-[0.2em] text-brand"><span className="size-2 rounded-full bg-success" /> Workspace / today</div><h1 className="max-w-2xl text-balance font-heading text-4xl font-black tracking-tight md:text-6xl">Keep every customer moving forward.</h1><p className="mt-3 max-w-xl text-sm leading-6 text-inkSecondary">Your next best actions, customer conversations, and revenue signals in one calm place.</p></div><button onClick={askAI} disabled={loading} className="flex items-center justify-center gap-2 rounded-xl border border-ink bg-ink px-4 py-3 text-xs font-bold text-white hover:bg-brand disabled:opacity-60"><Sparkles className="size-4" />{loading ? "Thinking…" : "Ask for next move"}</button></div>
        <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Stat label="Open pipeline" value={statsLoading ? "…" : money(stats?.pipeline_value)} detail={statsError ? "Unavailable" : `${metric(stats?.open_deals)} opportunities`} icon={TrendingUp} tone="brand" /><Stat label="Won revenue" value={statsLoading ? "…" : money(stats?.won_value)} detail={statsError ? "Unavailable" : `${metric(stats?.won_deals)} closed won`} icon={WalletCards} /><Stat label="Customers" value={metric(stats?.contacts_count)} detail={statsError ? "Unavailable" : "in your workspace"} icon={Users} /><Stat label="To follow up" value={metric(stats?.pending_tasks)} detail={statsError ? "Unavailable" : "tasks awaiting action"} icon={Clock3} /></div>
        {statsError && <div className="mt-4 flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-bad/30 bg-surface p-4 text-sm"><span>Workspace metrics are unavailable right now.</span><button onClick={loadStats} className="btn-primary">Retry</button></div>}
        {insight && <div className="mt-4 rounded-2xl border border-brand/30 bg-ai-bg p-5"><div className="mb-2 flex items-center gap-2 text-xs font-bold text-brand"><Sparkles className="size-4" /> Suggested next move</div><p className="whitespace-pre-wrap text-sm leading-6 text-ink">{insight}</p></div>}
        <div className="mt-6 grid gap-5 lg:grid-cols-[1.35fr_.65fr]"><section className="rounded-2xl border border-border bg-surface p-5 md:p-6"><div className="mb-5 flex items-center justify-between"><div><h2 className="font-heading text-xl font-black">Today&apos;s work</h2><p className="mt-1 text-xs text-inkSecondary">Small actions that compound into retention.</p></div><button onClick={() => navigate("/app/activities")} className="text-xs font-bold text-brand">View all</button></div><div className="flex flex-col gap-2"><Action icon={Clock3} title={`${stats?.pending_tasks || 0} follow-ups need attention`} detail="Review your task queue and keep promises visible." to="/app/activities" /><Action icon={Users} title="Review new customers" detail="Qualify recent contacts and assign an owner." to="/app/contacts" /><Action icon={MessageCircle} title="Open the inbox" detail="Reply where context is freshest." to="/app/inbox" /></div></section><section className="rounded-2xl border border-border bg-ink p-5 text-white md:p-6"><div className="flex items-center justify-between"><div><div className="font-mono text-[10px] uppercase tracking-[0.18em] text-white/50">Quick actions</div><h2 className="mt-2 font-heading text-xl font-black">Keep momentum</h2></div><Plus className="size-5 text-brand" /></div><div className="mt-5 flex flex-col gap-2"><button onClick={() => navigate("/app/contacts?new=1")} className="flex items-center justify-between rounded-xl bg-white/10 px-3 py-3 text-left text-xs font-bold hover:bg-white/15">Add a customer <ArrowUpRight className="size-4" /></button><button onClick={() => navigate("/app/activities?new=1")} className="flex items-center justify-between rounded-xl bg-white/10 px-3 py-3 text-left text-xs font-bold hover:bg-white/15">Create follow-up <ArrowUpRight className="size-4" /></button><button onClick={() => navigate("/app/campaigns")} className="flex items-center justify-between rounded-xl bg-white/10 px-3 py-3 text-left text-xs font-bold hover:bg-white/15">Plan a campaign <ArrowUpRight className="size-4" /></button></div></section></div>
        <section className="mt-5 rounded-2xl border border-border bg-surface p-5 md:p-6"><div className="mb-5 flex items-center justify-between"><div><h2 className="font-heading text-xl font-black">Pipeline pulse</h2><p className="mt-1 text-xs text-inkSecondary">Where opportunities are sitting right now.</p></div><button onClick={() => navigate("/app/pipeline")} className="text-xs font-bold text-brand">Open pipeline</button></div><div className="grid grid-cols-2 gap-3 md:grid-cols-6">{["lead", "qualified", "proposal", "negotiation", "won", "lost"].map((stage) => { const item = stats?.by_stage?.[stage] || {}; return <div className="rounded-xl bg-bg p-3" key={stage}><div className="font-mono text-[9px] uppercase tracking-widest text-inkSecondary">{stage}</div><div className="mt-3 font-heading text-2xl font-black">{item.count || 0}</div><div className="mt-1 text-[11px] text-inkSecondary">{money(item.value)}</div></div>; })}</div></section><div className="mt-5 flex items-center gap-2 text-xs text-inkSecondary"><CheckCircle2 className="size-4 text-success" /> Live data from your CRM. Provider metrics appear only when recorded.</div></div></div>;
}
